spring:
  application:
    name: ms-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/master


server:
  port: ${PORT:8080}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin-eureka-username:admin-eureka-password@eureka-server:8761/eureka
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
